version: "2"
run:
  tests: true
  allow-parallel-runners: true
linters:
  enable:
    - gosec
    - misspell
    - revive
    - unconvert
  settings:
    gosec:
      excludes:
        - G104
    govet:
      enable:
        - shadow
      enable-all: false
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
      - tests/e2e
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - tests/e2e
