run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
    - unconvert
    - revive

linters-settings:
  govet:
    enable-all: false
    enable:
      - shadow
  gosec:
    excludes:
      - G104 # Errors unhandled in defers/logging
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
